### ISSUE TITLE
Unable to use GetProductName function

### ISSUE THREAD

**Issue by Ashark** [pedrolabonia/pydavinci#10]
There is a function GetProductName that should be available.

I use a hack to support launching my script from both pycharm and dr py3 console. See it [here](https://gitlab.com/AndrewShark/davinci-resolve-scripts/-/blob/f113e0cf86f4ff91ce5e1cd126a7c356a9e178ea/mp4%20audio%20compounder.py#L14-22)

It is only about already having the resolve object in dr py3 while not having it immediately in pycharm. 

After that point I am sure I have resolve object. And then I can use `product = resolve.GetProductName()`.

However, with your library, I do not have it:
```python3
from pydavinci import davinci
resolve = davinci.Resolve()
product = resolve.GetProductName()
# AttributeError: 'Resolve' object has no attribute 'GetProductName'
```

**Desktop (please complete the following information):**
 - OS: Arch
 - Python Version: 3.6.11
 - Davinci Resolve Version: 18.0b1

**Comment by pedrolabonia** [comment]
Hi Ashark,

This is a wrapper around the API, intended for a more pythonic use. One result of that is not using `CamelCase` functions.

Try using `resolve.product_name`

Please check out the [documentation](https://pedrolabonia.github.io/pydavinci/resolve/)

**Comment by pedrolabonia** [comment]
@Ashark ,

just updated the docs. They were deployed with a old documentation build. 

You should be able to see[ `resolve.product_name`](https://pedrolabonia.github.io/pydavinci/resolve/#pydavinci.wrappers.resolve.Resolve.product_name) under attributes now.

**Comment by Ashark** [comment]
Oh, I see now. This is not just an auto completion thing, it remakes them. Ok. But I still have a problem.
```python
resolve = davinci.Resolve()
product = resolve.product_name
```

Traceback contains the following text:
```
File "/home/andrew/.pyenv/versions/3.6.11/lib/python3.6/site-packages/pydavinci/wrappers/resolve.py", line 123, in product_name
    return self._obj.GetProductName()
AttributeError: 'NoneType' object has no attribute 'GetProductName'
```

**Comment by pedrolabonia** [comment]
Where's your fusionscript module located? Can you call other methods? Is Davinci resolve running?

Are you using the free version? Are you able to externally script Davinci without using `pydavinci` ?
