### ISSUE TITLE
get_metadata() - optional argument is actually required - DR18

### ISSUE THREAD

**Issue by ChristyKail** [pedrolabonia/pydavinci#12]
The docs state that calling mediapoolitem.get_metadata() with no argument will return a dict with all availible metadata, however i'm finding it throws a `required positional argument` error

**To Reproduce**
```
from pydavinci import davinci
import sys

resolve = davinci.Resolve()

media_pool = resolve.media_pool
root = media_pool.root_folder

all_clips = root.clips

for clip in all_clips:

	for item in clip.get_metadata():

		print(item)
```
Traceback i'm recieving:

```
Traceback (most recent call last):
  File "/Users/a_user_name/PyDavinciTests.py", line 18, in <module>
    for item in clip.get_metadata():
TypeError: get_metadata() missing 1 required positional argument: 'metadata_key'
```

**System:**
 - OS: MacOS Catalina (Macbook Pro 2019)
 - Python Version: 3.9.12
 - Davinci Resolve Version: 18.0B Build 7

Obviously I'm aware I'm running this on an unsupported version, so sorry if this is a problem on my end and not with the module. (Also if I've just written a buggy script!)
It's AvidResolver from Reddit here BTW.

**Comment by pedrolabonia** [comment]
Hey @ChristyKail ,

uuh, that was my bad. For now, you can use ``get_metadata(None)``. I forgot to set `None` as default. 

Note though that it will only return the metadata from here:

![image](https://user-images.githubusercontent.com/4316044/165413601-a953e8b1-b1ae-4675-890c-8117b3f56987.png)


I'm working on some other changes and I'll patch this issue soon. I'll leave the issue open for when the patch is done. Meanwhile, I'll update the docs.

**Comment by pedrolabonia** [comment]
Docs are updated, there was a similar issue on `project.get_setting`. Using `None` or an empty string works for now.
