### ISSUE TITLE
GetTimelineByIndex(...) wrapper missing

### ISSUE THREAD

**Issue by Topassi** [pedrolabonia/pydavinci#18]
Hi there,
I miss the wrapper for GetTimelineByIndex(...) in pydavinci/wrappers/project.py.
The implementation of open_timeline(...) already shows a call of  Timeline(self._obj.GetTimelineByIndex(i + 1)), so this looks like a straight forward enhancement. Some pseudo code:

    def get_timeline(self, index: int) -> "Timeline":
        """
        Returns timeline by index.
        Args:
            index (int): 1 <= index <= timeline_count
        Returns:
            "Timeline": ``Timeline`` if successful, ``None`` otherwise
        """
        from pydavinci.wrappers.timeline import Timeline

        return Timeline(self._obj.GetTimelineByIndex(index))

It would be helpful if you could add this. Thank you.
Thomas

**Comment by pedrolabonia** [comment]
Hi Thomas,

not implementing that was a conscious choice, since that function is usually used to iterate over timelines and find the one you're looking for, which usually is found using the name.

Can you describe your use case?

**Comment by Topassi** [comment]
Hi Pedro,
while I am working on a video project 'Name', I create versions by adding a postfix like -A, -B, -C etc. to the timelines' name.

Based on the timeline_count property in Project, I iterate over all timelines using project._obj.GetTimelineByIndex(i + 1) as a workaround. Finally, after some filtering, I create a reverse sorted list Name-C, Name-B, Name-A and pick the first entry to name a new copy Name-D. 

If there would be another way to get a list of all timelines (maybe I overlooked that), I could also adapt. 

Thank you for getting back to me,
Thomas

**Comment by in03** [comment]
Hi Pedro,
Thanks for all your hard work on this! 
I recently stumbled upon the same issue as Thomas. I frequently need to iterate all timelines and there doesn't seem to be an easy way to get a timeline object without opening a timeline by name. The `GetTimelineByIndex()` function isn't exactly elegant, but could we do something like this? 

Happy to submit a PR 😄 👍 

```python
    @property
    def timelines(self) -> list:
        """
        Returns all timelines
        
        Returns:
            list: timelines
        """
        
        from pydavinci.wrappers.timeline import Timeline

        timelines = []
        count = self._obj.GetTimelineCount()
        for i in range(count):
            timelines.append(Timeline(self._obj.GetTimelineByIndex(i + 1)))
        
        return timelines
```

**Comment by pedrolabonia** [comment]
Sure, @in03 !

Feel free to open a PR! I've been meaning to fix these issues, but work just has gotten to me and I haven't been able to find time.

Also have been meaning to fully support DR 18.

Thank you!

**Comment by in03** [comment]
@pedrolabonia 

Awesome! Thanks. I should be free to get onto that this Monday.

Also I'm running Resolve 18 atm and so far works a charm. I do like to develop using poetry though, which doesn't allow ignoring required python version unfortunately... so I'm running my projects off my own fork of pydavinci atm. I suppose the only way to juggle support for 17 and 18 without having separate packages is to check at runtime?
