### ISSUE TITLE
Support Resolve 18

### ISSUE THREAD

**Issue by in03** [pedrolabonia/pydavinci#22]
Also I'm running Resolve 18 atm and so far works a charm. I do like to develop using poetry though, which doesn't allow ignoring required python version unfortunately... so I'm running my projects off my own fork of pydavinci atm. I suppose the only way to juggle support for 17 and 18 without having separate packages is to check at runtime?

_Originally posted by @in03 in https://github.com/pedrolabonia/pydavinci/issues/18#issuecomment-1272288384_

**Comment by pedrolabonia** [comment]
Closed with your great work https://github.com/pedrolabonia/pydavinci/commit/17c8c10c102e8dcdae96f881c5f367976165fe37

:)
