### ISSUE TITLE
Roadmap, additional maintainers?

### ISSUE THREAD

**Issue by in03** [pedrolabonia/pydavinci#24]
**Is your feature request related to a problem? Please describe.**
Love your work! :heart: I can see the sheer amount of work you've put into this.
I'm slowly chipping away at missing wrappers I'd like. I've been working on the gallery ones atm.
Unfortunately, I can't publish my own PyPi packages using my fork of your project as a URL. PyPi doesn't seem to accept packages that have dependencies with git repository sources. And I certainly **don't** want to publish a fork of pydavinci to PyPi as a workaround...

I'm still getting my head around pydavinci. I don't have much experience with wrappers or stubs, but I'm learning. I'd love to help out in a greater capacity, especially if it means I can use some of Resolve's newer features in Pydavinci and publish to PyPi. I hope this doesn't sound pushy at all, but maybe what I'm asking is:

- What are your plans for the future of pydavinci?
- How much time do you have realistically to maintain pydavinci (approve pull requests, tests, etc?)
- How much time do you have to offer support to contributors and users?
- Is it feasible to allow additional maintainers, admin, etc?

**Describe the solution you'd like**
Obviously pydavinci is your baby and I don't want to overstep... 
Maybe you could consider adding me as a maintainer? I'm using Python and scripting for Resolve almost every day as part of my job. I'd love to be able to give back as much as I can. Especially in a collaborative project. There isn't a heap of community around scripting for Resolve, but it's starting to get bigger. Having an up-to-date wrapper with typing and intellisense support is a fantastic head start for new projects.

**Comment by pedrolabonia** [comment]
Hey @in03 ! Sorry for the delay.

I just added you on Discord. Let's talk! :)
