### ISSUE TITLE
Moving timeline playhead

### ISSUE THREAD

**Issue by MarcoP91** [pedrolabonia/pydavinci#27]
First of all, thank you very much for this repo, I am enjoying it a lot.

I wanted to ask, is there a way to move the playhead? If I add to the timeline a list of MediaPoolItems, they get added one after another; I would like to add a video and an audio file "at the same time". Is that possible? If not, is there a way to set the time location of a MediaPoolItem?

**Comment by MarcoP91** [comment]
I have done it:

timeline.settings._obj.GetCurrentTimecode() to get the current playhead position 

timeline.settings._obj.SetCurrentTimecode('01:00:20:00') to move it to the specified position

**Comment by MarcoP91** [comment]
My bad, by using mediapool.append_to_timeline() the new clips get added at the end nonetheless. }
Is there a way to modify the time location of a MediaPoolItem?

**Comment by in03** [comment]
Hey @MarcoP91! Pydavinci doesn't fully support all of Resolve's API yet, but unfortunately I don't think even Resolve's API supports inserting clips into timeline yet...  I haven't got Resolve handy atm, but you can check the scripting README in your copy of Resolve to see what's supported.

**Comment by MarcoP91** [comment]
Ok, thank you 👍

I created a workaround with osascript, I'll leave it here:

`query = f"""
    osascript -e '
        tell application "Davinci Resolve"
            activate
            delay 0.1
            tell application "System Events"
              key code 123
              delay 0.1
              key code 123
              delay 0.1
              keystroke "y"
              delay 0.1
            keystroke "d" using command down
            delay 0.1
            keystroke "{seconds}"
            delay 0.1
            keystroke return
            end tell
        end tell

    '
    """
    os.system(query)`

**Comment by SW-Daren** [comment]
Apparently AppendToTimeline() has some new parameters in DR 18 that allows for this. See this forum thread for details: [](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=113040)

**Comment by LittleTerry** [comment]
> Apparently AppendToTimeline() has some new parameters in DR 18 that allows for this. See this forum thread for details: https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=113040

cool!

**Comment by pedrolabonia** [comment]
Fixed in by #28 

Closed
