### ISSUE TITLE
very cool project!

### ISSUE THREAD

**Issue by LittleTerry** [pedrolabonia/pydavinci#31]
Very cool project! Thanks for your hard work!
Hope more features can be added to fit with Davinci 18!
Many thanks!!!!

**Comment by LittleTerry** [comment]
> 

For example, can we write text in Davinci with pydavinci?

**Comment by pedrolabonia** [comment]
Hi @LittleTerry,

This probably can be achieved with the Fusion API, but unfortunately it's out of the scope of this project.

Pedro
